import nodemailer from 'nodemailer';

export const transport = nodemailer.createTransport({
  host: 'smtp.gmail.com',
  port: 465,
  secure: true,
  auth: {
    user: 'jobportalrgt@gmail.com', ////1290--pin
    pass: 'ddnj qqux yccg vdht'  //pass key generated by app pass
  }
});
